DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS user_badges;
DROP TABLE IF EXISTS badges;
DROP TABLE IF EXISTS user_xp;
DROP TABLE IF EXISTS completions;
DROP TABLE IF EXISTS streaks;
DROP TABLE IF EXISTS goals;
DROP TABLE IF EXISTS users;
